---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(Hmisc)
library(statmod)
```


### Read in Files
```{r}
spills_clean = read_csv("../data/spills_clean.csv")

spills_clean %>% 
  select_if(function(x) any(is.na(x))) %>% 
  summarise_each(funs(sum(is.na(.))))

#spills_clean = spills_clean %>% drop_na()
```

```{r}
storage_clean = read_csv("../data/storage_clean.csv")
```

```{r}
storage_clean %>% select(Tank.Location) %>% unique()
```



## Define Useful Cleaning Functions
```{r}
clean_date_str = function(date_str) {
  mdy = mdy(date_str)
  ymd = ymd(date_str)
  
  if(is.na(mdy)){
    if(is.na(ymd)){
      return(NA)
    }
    else {return(ymd)}
  }
  else {return(mdy)}
}

# fmt_df_dates = function(df) {
#   df = df %>% mutate('START.DATE' = clean_data_str(START.DATE), 'END.DATE' = clean_data_str(END.DATE))
#   return(df)

clean_text_col = function(txt) {
  # Remove all chars not letters or spaces
  txt = gsub("[^[:alnum:]#()-]", " ", txt)
  
  # Change all chars to lower
  txt = tolower(txt)
  
  # Remove other
  txt = gsub("other", "", txt)
  
  # Replace all multi space with single space
  # Remove all white space in begin and end
  txt = gsub("\\s+", " ", str_trim(txt))
  return(txt)
}
library(lubridate)
```


## Cleaning 

```{r}
spills_clean$`Spill Date` = clean_date_str(spills_clean$`Spill Date`)
spills_clean$`Received Date` = clean_date_str(spills_clean$`Received Date`)
spills_clean$`Close Date` = clean_date_str(spills_clean$`Close Date`)

storage_clean$`Install Date` = clean_date_str(storage_clean$`Install Date`)
storage_clean$`Close Date` = clean_date_str(storage_clean$`Close Date`)
storage_clean$`Expiration Date` = clean_date_str(storage_clean$`Expiration Date`)


```

## Generate Report Lag for Spill Data
```{r}
spills_clean = spills_clean %>% 
  mutate('Report Lag' = as.numeric(difftime(`Received Date`,`Spill Date`,units = 'days')),
         'Case Lag' = as.numeric(difftime(`Close Date`,`Spill Date`,units = 'days')))
  
```

```{r}
storage_clean %>% rename(
  "Program.Type"="Program Type",
  "Site.Type"="Site Type Name", 
  "Facility.Name"="Program Facility Name", 
  'Address'="Address 1", 
  'ZIP'="ZIP Code",
  "DEC.Region"=`NYSDEC Region`,
  'Tank.Location'=`Tank Location`,
  'Tank.Status'=`Tank Status`,
  "Install.Date"=`Install Date`,
  "Quantity"=`Capacity in Gallons`,
  "Tank.Type"=`Tank Type`,
  "Close.Date" = `Close Date`,
  "Material"=`Material Name`,
  "Exp.Date" = `Expiration Date`,
  "Site.Status" = `Site Status Name`
)
```

```{r}
storage_clean %>% select(Tank.Status) %>% unique()
```

```{r}
library(tidyverse)
storage_clean = storage_clean %>%
  mutate('label' = paste0(Facility.Name,', Tank: ',Tank.Status,", ", Material))
```

```{r}
spills_clean = spills_clean %>%
  mutate('label' = paste0(format(`Spill Date`,'%b %d, %Y'),': ',Source,' Spill of ',Quantity,' Gal of ',Material))
```


```{r}
spills_clean = spills %>%
  mutate(Locality = gsub(".*New City.*", "Manhattan", Locality,perl=TRUE)) %>%
  mutate(Locality = gsub(".*Ny.*", "Manhattan", Locality,perl=TRUE)) %>%
  mutate(Locality = gsub(".*NA.*", "Manhattan", Locality,perl=TRUE)) %>% 
  mutate(Locality = gsub(".*Newyork City.*", "Manhattan", Locality,perl=TRUE)) %>% 
  mutate(Locality = gsub(".*Ny City.*", "Manhattan", Locality,perl=TRUE)) %>% 
  mutate(Locality = gsub(".*New York (Manhattan).*", "Manhattan", Locality,perl=TRUE)) %>%
  mutate(Locality = gsub(".*New.*", "Manhattan", Locality,perl=TRUE)) %>% 
  mutate(Locality = gsub(".*Ny Ny.*", "Manhattan", Locality,perl=TRUE)) %>%  
  mutate(Locality = gsub(".*New York New York.*", "Manhattan", Locality,perl=TRUE)) %>%  
  mutate(Locality = gsub(".*Statton Island.*", "Staten Island", Locality,perl=TRUE)) %>% 
  mutate(Locality = gsub(".*Statenisland.*", "Staten Island", Locality,perl=TRUE)) %>%  
  mutate(Locality = gsub(".*Manhateen.*", "Manhattan", Locality,perl=TRUE)) %>%  
  mutate(Locality = gsub(".*Manhattam.*", "Manhattan", Locality,perl=TRUE)) %>% 
  mutate(Locality = gsub(".*West Broadway, Manhattan.*", "Manhattan", Locality,perl=TRUE)) %>% 
  mutate(Locality = gsub(".*Jamaica Bay.*", "Queens", Locality,perl=TRUE)) %>% 
  mutate(Locality = gsub(".*Wards Island Complex.*", "Wards Island", Locality,perl=TRUE)) %>% 
  mutate(Locality = gsub(".*Manhatten.*", "Manhattan", Locality,perl=TRUE)) %>% 
  mutate(Locality = gsub(".*Man.*", "Manhattan", Locality,perl=TRUE)) %>% 
  mutate(Locality = gsub(".*New York.*", "Manhattan", Locality,perl=TRUE)) %>% 
  mutate(Locality = gsub(".*Ney York.*", "Manhattan", Locality,perl=TRUE)) %>% 
  mutate(Locality = gsub(".*New York Harbor.*", "Manhattan", Locality,perl=TRUE)) %>% 
  mutate(Locality = gsub(".*Bronxs.*", "Bronx", Locality,perl=TRUE)) %>% 
  mutate(Locality = gsub(".*Brookln.*", "Brooklyn", Locality,perl=TRUE)) %>% 
  mutate(Locality = gsub(".*East Harlem.*", "Harlem", Locality,perl=TRUE))
  
  
```

```{r}
spills_clean %>% 
  filter(County == 'New York') %>% 
  select(Locality, County) %>% 
  arrange(Locality) %>% 
  unique()
```



```{r}
petrols = spills_clean %>% filter(`Material Family` == 'Petroleum') %>% select(`Material Name`) %>% unique()

petchem = spills_clean %>% filter(`Material Family` == 'Petrochemical') %>% select(`Material Name`) %>% unique()

commodity = spills_clean %>% filter(`Material Family` == 'Commodity Chemical') %>% select(`Material Name`) %>% unique()

hazard = spills_clean %>% filter(`Material Family` == 'Hazardous Material') %>% select(`Material Name`) %>% unique()

green = spills_clean %>% filter(`Material Family` == 'Greenhouse Gas') %>% select(`Material Name`) %>% unique()


```




```{r}

colnames(spills_clean)
spills_clean$Waterbody = spills_clean$Waterbody %>% replace(is.na(.),'N/A')
```


```{r}
storage_clean = storage_clean %>% 
  semi_join(spills, by = c('Material' = 'Material Name'))

spills_clean = spills_clean %>% 
  semi_join(storage_clean, by = c('County'))
```


```{r}
storage_clean$`DEC Region` = as.factor(storage_clean$`DEC Region`)
spills_clean$`DEC Region` = as.factor(spills_clean$`DEC Region`)
```

```{r}
spills_clean %>% select(Source) %>% unique()


spills_clean = spills_clean %>% mutate('Source_' = case_when(
  Source == 'Tank Truck' ~ "Vehicle",
  Source == 'Institutional, Educational, Gov., Other' ~ "Municipal",
  Source == 'Railroad Car' ~ "Vehicle",
  Source == 'Gasoline Station or other PBS Facility' ~ "Petroleum Storage",
  Source == 'Commercial Vehicle' ~ "Vehicle",
  Source == 'Private Dwelling' ~ "Other",
  Source == 'Commercial/Industrial' ~ "Industrial",
  Source == 'Unknown' ~ "Other",
  Source == 'Non Major Facility > 1,100 gal' ~ "Petroleum Storage",
  Source == 'Vessel' ~ "Vehicle",
  Source == 'Major Facility (MOSF) > 400,000 gal' ~ "Petroleum Storage",
  Source == 'Passenger Vehicle' ~ "Vehicle",
  Source == 'Missing Code in Old Data - Must be fixed' ~ "Other",
  Source == 'Transformer' ~ "Municipal",
  Source == 'Airport/Aircraft' ~ "Vehicle",
  Source == 'Chemical Bulk Storage Facility' ~ "Chemical Storage"
))
```
```{r}

spills_clean = rename(spills_clean,
                      "Contributing.Factor"  = "Contributing Factor" ,
                      "Facility.Name" = "Program Facility Name",
                      "DEC.Region" = "DEC Region"
                      )
colnames(spills_clean)
```

```{r}
spills_clean = spills_clean %>% rename(
    "Material" = "Material Name"
  )
  
```


```{r}
library(tools)

```

```{r}
storage_clean$Address = toTitleCase(tolower(storage_clean$Address))
storage_clean$Locality = toTitleCase(tolower(storage_clean$Locality))
storage_clean$Material = toTitleCase(tolower(storage_clean$Material))
```

```{r}
spills_clean$Material = toTitleCase(tolower(spills_clean$Material))
```



### Write to directory
```{r}
write_csv(spills_clean, '../data/spills_clean.csv')
write_csv(storage_clean, '../data/storage_clean.csv')
```


### Visualizations
```{r}
colours = c("Petroleum" = colors[1], 
            "Greenhouse Gas" = colors[2], 
            "Hazardous Material" = colors[3], 
            "Petrochemical" = colors[4], 
            "Commodity Chemical" = colors[5])

spills_cleaner = spills_clean %>% 
  semi_join(storage, by = c('Material Name' = 'Material.Name'))

spills_cleaner %>% 
  group_by(`Source`,`Material Family`) %>% 
  summarise(total = log(sum(Quantity))) %>% 
  ggplot(aes(x = reorder(Source,total), y = total)) +
  geom_col(aes(fill=`Material Family`)) +
  scale_fill_manual(values = colours) +
  coord_flip() +
  labs(y='Total Spilled (log-scale)',
       x='') +
  scale_fill_brewer(palette='Set1') +
  theme_bw() +
  theme(legend.key=element_blank())

```

```{r}
library(scales)
county_name = 'Albany'
county_spills = spills %>% 
  semi_join(storage, by = c('Material Name' = 'Material.Name')) %>% 
  filter(County == county_name) %>% 
  group_by(`Material Name`) %>% 
  summarise(total_spilled = sum(Quantity)) %>% 
  arrange(desc(total_spilled)) %>% 
  slice(1:10)

county_spills %>% 
  ggplot(aes(x = reorder(`Material Name`,total_spilled), y = `total_spilled`)) +
  geom_point()+
  scale_y_continuous(trans='log10',
                     breaks = trans_breaks("log10", function(x) 10^x),
                     labels = trans_format("log10", math_format(10^.x))) +
  coord_flip() +
  labs(y='Total Spilled (Gallons)',
       x='') +
  scale_fill_brewer(palette='Set1') +
  theme_bw() +
  theme(legend.key=element_blank())
```


```{r}
library(scales)
g = monthly_spills %>% ggplot(aes(x = month, y= count)) +
  geom_point() + facet_wrap(~year) 
  labs(title = 'Chemical Spills in Albany',
    y='Number of Spills',
       x='Month') +
  scale_x_discrete(labels=month.abb)

g
```

```{r}
ganim = g + transition_time(year) + labs(title = "Year: {frame_time}")
animate(ganim, fps=10)
```
```{r}
g + transition_time(year) + labs(title = "Year: {frame_time}")
```

## Analysis of County Data Spills based on Year and Month
```{r}
spills %>% 
  mutate(month = month(`Spill Date`), year = year(`Spill Date`)) %>% 
  group_by(County, year, month) %>% 
  summarise(num_spills = n())
  
```

### Analysis by County
```{r}
county_name = 'Albany'

# Facility Closures
facility_closures = storage %>% 
  filter(County.Name==county_name) %>% 
  select(Close.Date) %>% 
  mutate('year_mon'= format(as.Date(Close.Date), "%Y-%m")) %>% 
  #rename("Date" = 'Close.Date') %>% 
  group_by(year_mon) %>% 
  #group_by(year,month) %>% 
  summarise(closures = n(), mean_closures = closures/30)

num_spills = spills %>% 
  filter(County==county_name) %>% 
  mutate('year_mon' = format(as.Date(`Spill Date`), "%Y-%m")) %>% 
  #rename("Date" = 'Spill Date') %>% 
  group_by(year_mon) %>% 
  #group_by(year, month) %>% 
  summarize(spills = n(), mean_spills = spills/30)

```


```{r}
closures_and_spills = facility_closures %>% full_join(., num_spills, by="year_mon")
```

```{r}
closures_and_spills_year = closures_and_spills %>%
  mutate('year' = substring(year_mon,1,4)) %>% 
  group_by(year) %>% 
  summarise(closures = sum(closures, na.rm = TRUE), spills= sum(spills, na.ram=TRUE))

```

```{r}
str(closures_and_spills_year)
```


```{r}

closures_and_spills_year %>% 
  ggplot(aes(x = year, group=2)) + 
  geom_path(aes(y = closures)) + 
  geom_path(aes(y = spills, col = "blue")) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  scale_x_date(breaks = 10)
```


```{r}
storage %>% 
  filter(County.Name==county_name) %>% 
  mutate('year_mon'= format(as.Date(Close.Date), "%Y-%m")) %>% 
  #rename("Date" = 'Close.Date') %>% 
  group_by(Close.Date) %>% 
  mutate(num = n()) %>% 
  select(year_mon, num) %>% 
  group_by(year_mon) %>% 
  summarize(mean = mean(num))
```




## Total Closures
```{r}
# Facility Closures
facility_closures = storage %>% 
  select(Close.Date) %>% 
  mutate('year_mon'= format(as.Date(Close.Date), "%Y-%m")) %>% 
  #rename("Date" = 'Close.Date') %>% 
  group_by(year_mon) %>% 
  #group_by(year,month) %>% 
  summarise(closures = n(), mean_closures = closures/30)

num_spills = spills %>% 
  mutate('year_mon' = format(as.Date(`Spill Date`), "%Y-%m")) %>% 
  #rename("Date" = 'Spill Date') %>% 
  group_by(year_mon) %>% 
  #group_by(year, month) %>% 
  summarize(spills = n(), mean_spills = spills/30)

closures_and_spills = facility_closures %>% full_join(., num_spills, by="year_mon")


closures_and_spills_year = closures_and_spills %>%
  mutate('year' = substring(year_mon,1,4)) %>% 
  group_by(year) %>% 
  summarise(closures = sum(closures, na.rm = TRUE), spills= sum(spills, na.ram=TRUE))


closures_and_spills_year %>% 
  ggplot(aes(x = year, group=2)) + 
  geom_path(aes(y = closures)) + 
  geom_path(aes(y = spills, col = "blue")) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))
```

```{r}
spills %>% 
  group_by(Material.Family) %>% 
  ggplot(aes(Material.Family,log(Quantity))) +
  geom_violin(scale="area", fill='#c4200e') + stat_summary(fun.data=mean_sdl, mult=1, 
                 geom="pointrange", color="green")
  
```
```{r}
offenders = storage %>% 
  inner_join(spills, by=c('Facility.Name','Locality','County','DEC.Region')) %>% 
  select(Facility.Name,Locality,County,Quantity.x,Quantity.y, `Case Lag`) %>% 
  group_by(Facility.Name) %>% 
  filter(`Case Lag` > 0 & `Case Lag` < 1e3) %>% 
  summarise(tank_cap = sum(Quantity.x), spill_volume = sum(Quantity.y), num_spills = n(), case.lag = median(`Case Lag`)) %>%
  arrange(desc(spill_volume)) %>% 
  slice(1:20) 
```

```{r}
offenders %>% 
  ggplot(aes(x = reorder(Facility.Name,spill_volume)), groups=2) +
  geom_point(aes(y = spill_volume), color = 'purple') +
  geom_point(aes(y = tank_cap), color = 'blue') +
  geom_col(aes(y=case.lag), color = 'black', alpha=0.5) +
  coord_flip() +
  scale_y_log10(breaks = trans_breaks("log10", function(x) 10^x),
                          labels = trans_format("log10", math_format(10^.x))) +
  labs(y = 'Log of Total Volume')
```

```{r}
offenders_num = offenders %>% select(-Facility.Name)
cor(offenders_num, method = "pearson", use = "complete.obs")

```
```{r}
offenders
```

```{r}
offenders %>% 
  ggplot(aes(x=tank_cap,y=num_spills)) + geom_point()
```

