---
title: "R Notebook"
output: html_notebook
---

```{r}
library(lubridate)
library(tidyverse)

clean_date_str = function(date_str) {
  mdy = mdy(date_str)
  ymd = ymd(date_str)
  
  if(is.na(mdy)){
    if(is.na(ymd)){
      return(NA)
    }
    else {return(ymd)}
  }
  else {return(mdy)}
}

# fmt_df_dates = function(df) {
#   df = df %>% mutate('START.DATE' = clean_data_str(START.DATE), 'END.DATE' = clean_data_str(END.DATE))
#   return(df)

clean_text_col = function(txt) {
  # Remove all chars not letters or spaces
  txt = gsub("[^[:alnum:]#()-]", " ", txt)
  
  # Change all chars to lower
  txt = tolower(txt)
  
  # Remove other
  txt = gsub("other", "", txt)
  
  # Replace all multi space with single space
  # Remove all white space in begin and end
  txt = gsub("\\s+", " ", str_trim(txt))
  return(txt)
}

  storage_clean = read_csv("../data/raw_data.csv")
  storage_clean = select(storage_clean, -c('Program Number','Location 1','Address 2','Tank Number','NYS Municipal Boundaries','New York Zip Codes','Counties'))
  
  storage_clean = storage_clean %>% rename(
    "Program.Type"="Program Type",
    "Site.Type"="Site Type Name", 
    "Facility.Name"="Program Facility Name", 
    'Address'="Address 1", 
    'ZIP'="ZIP Code",
    "DEC.Region"=`NYSDEC Region`,
    'Tank.Location'=`Tank Location`,
    'Tank.Status'=`Tank Status`,
    "Install.Date"=`Install Date`,
    "Quantity"=`Capacity in Gallons`,
    "Tank.Type"=`Tank Type`,
    "Close.Date" = `Close Date`,
    "Material"=`Material Name`,
    "Exp.Date" = `Expiration Date`,
    "Site.Status" = `Site Status Name`
  )
  
  
  # Date Clean
  storage_clean$`Install.Date` = clean_date_str(storage_clean$`Install.Date`)
  storage_clean$`Close.Date` = clean_date_str(storage_clean$`Close.Date`)
  storage_clean$`Exp.Date` = clean_date_str(storage_clean$`Exp.Date`)
  
  
  
  storage_clean = storage_clean %>% 
    mutate(Material = gsub("kerosene [#1 fuel oil] (on-site consumption)", "#1 fuel oil", Material,ignore.case = F, fixed = T)) %>% 
    mutate(Material = gsub("kerosene [#1 fuel oil] (resale/redistribute)", "#1 fuel oil", Material,ignore.case = F, fixed = T)) %>% 
    mutate(Material = gsub("#2 fuel oil (on-site consumption)", "#2 fuel oil", Material,ignore.case = F, fixed = T)) %>% 
    mutate(Material = gsub("#2 fuel oil (resale/redistribute)", "#2 fuel oil", Material,ignore.case = F, fixed = T)) %>% 
    mutate(Material = gsub("#4 fuel oil (on-site consumption)", "#4 fuel oil", Material,ignore.case = F, fixed = T)) %>% 
    mutate(Material = gsub("#4 fuel oil (resale/redistribute)", "#4 fuel oil", Material,ignore.case = F, fixed = T)) %>% 
    mutate(Material = gsub("#5 fuel oil (on-site consumption)", "#5 fuel oil", Material,ignore.case = F, fixed = T)) %>% 
    mutate(Material = gsub("#5 fuel oil (resale/redistribute)", "#5 fuel oil", Material,ignore.case = F, fixed = T)) %>% 
    mutate(Material = gsub("#6 fuel oil (on-site consumption)", "#6 fuel oil", Material,ignore.case = F, fixed = T)) %>% 
    mutate(Material = gsub("#6 fuel oil (resale/redistribute)", "#6 fuel oil", Material,ignore.case = F, fixed = T)) %>%
    mutate(Material = gsub("gasoline/ethanol", "ethanol", Material,ignore.case = F, fixed = T)) %>% 
    mutate(Material = gsub("Diesel (E-Gen)", "diesel", Material,ignore.case = F, fixed = T)) %>% 
    mutate(Material = gsub("used oil (heating, on-site consumption)", "used oil (heating)", Material,ignore.case = F, fixed = T)) %>% 
    mutate(Material = gsub("waste oil/used oil", "waste oil", Material,ignore.case = F, fixed = T)) %>% 
    mutate(Material = gsub("Biodiesel (E-Gen)", "biodiesel", Material,ignore.case = F, fixed = T)) %>% 
    mutate(Material = gsub("biodiesel (heating, on-site consumption)", "biodiesel", Material,ignore.case = F, fixed = T)) %>% 
    
    mutate(Site.Type = gsub("Municipality (Incl. Waste Water Treatment Plants, Utilities, Swimming Pools, etc.)", "Municipality", Site.Type,ignore.case = F, fixed = T)) %>% 
    mutate(Site.Type = gsub("Religious Building (Church, Synagogue, Mosque, Temple, etc.)", "Relgious Building", Site.Type,ignore.case = F, fixed = T)) %>% 
    mutate(Site.Type = gsub("Manufacturing (Other than Chemical)/Processing", "Non-Chemical Manufacturing/Processing", Site.Type,ignore.case = F, fixed = T)) %>% 
    mutate(Site.Type = gsub("Unknown", "Other", Site.Type,ignore.case = F, fixed = T)) %>% 
    mutate(Site.Type = gsub("Apartment Building/Office Building", "Apartment/Office Building", Site.Type,ignore.case = F, fixed = T)) %>% 
    mutate(Site.Type = gsub("Other Wholesale/Retail Sales", "Retail Gasoline Sales", Site.Type,ignore.case = F, fixed = T)) %>% 
    mutate(Site.Type = gsub("Auto Service/Repair (No Gasoline Sales)", "Auto Service", Site.Type,ignore.case = F, fixed = T)) %>% 
    mutate(Site.Type = gsub("Storage Terminal/Petroleum Distributor", "Petroleum Storage/Distribution", Site.Type,ignore.case = F, fixed = T)) %>% 
    mutate(Site.Type = gsub("Hospital/Nursing Home/Health Care", "Hospital/Health Care", Site.Type,ignore.case = F, fixed = T)) %>% 
    mutate(Site.Type = gsub("Airport/Airline/Air Taxi", "Airport", Site.Type,ignore.case = F, fixed = T)) %>% 
    mutate(Site.Type = gsub("Trucking/Transportation/Fleet Operation", "Trucking/Transport", Site.Type,ignore.case = F, fixed = T)) %>% 
    
    mutate(Tank.Location = gsub("Aboveground - in contact with impervious barrier", "Aboveground (impervious barrier)", Tank.Location,ignore.case = F, fixed = T)) %>% 
    mutate(Tank.Location = gsub("Underground including vaulted with no access for inspection", "Underground (no access)", Tank.Location,ignore.case = F, fixed = T)) %>% 
    mutate(Tank.Location = gsub("Aboveground - in contact with soil", "Aboveground (soil contact)", Tank.Location,ignore.case = F, fixed = T)) %>% 
    mutate(Tank.Location = gsub("Aboveground on saddles, legs, stilts, rack or cradle"  ,"Aboveground (no ground contact)", Tank.Location,ignore.case = F, fixed = T)) %>%
    mutate(Tank.Location = gsub("Aboveground in Subterranean vault with access for inspections", "Aboveground (subterranean, with access)", Tank.Location,ignore.case = F, fixed = T)) %>% 
    mutate(Tank.Location = gsub("Tank with 10% or more below ground", "Tank (>10% below ground)", Tank.Location,ignore.case = F, fixed = T)) %>% 
    mutate(Locality = gsub("new york city", "new york", Locality,ignore.case = F, fixed = T)) %>% 
    mutate(County = gsub("New York City", "New York", County ,ignore.case = F, fixed = T))
```

```{r}
storage_clean = clean_storage(storage_clean)
```


```{r}
storage = storage %>% 
  mutate(Tank.Status = gsub("Tank Converted to Non-Regulated use", "Converted to Non-Regulated Use", Tank.Status,ignore.case = F, fixed = T))
```

```{r}
source('clean.R')
```


```{r}
storage_clean = storage_clean %>% 
  mutate(Tank.Type = gsub("Missing Code in Old Data - Must be fixed", "Missing Code", Tank.Type,ignore.case = F, fixed = T)) %>% 
  mutate(Tank.Type = gsub("Steel/Carbon Steel/Iron", "Steel", Tank.Type,ignore.case = F, fixed = T))

```



```{r}
storage = storage %>% 
  mutate(Material.Name = gsub("kerosene [#1 fuel oil] (on-site consumption)", "#1 fuel oil", Material.Name,ignore.case = F, fixed = T)) %>% 
  mutate(Material.Name = gsub("kerosene [#1 fuel oil] (resale/redistribute)", "#1 fuel oil", Material.Name,ignore.case = F, fixed = T)) %>% 
  mutate(Material.Name = gsub("#2 fuel oil (on-site consumption)", "#2 fuel oil", Material.Name,ignore.case = F, fixed = T)) %>% 
  mutate(Material.Name = gsub("#2 fuel oil (resale/redistribute)", "#2 fuel oil", Material.Name,ignore.case = F, fixed = T)) %>% 
  mutate(Material.Name = gsub("#4 fuel oil (on-site consumption)", "#4 fuel oil", Material.Name,ignore.case = F, fixed = T)) %>% 
  mutate(Material.Name = gsub("#4 fuel oil (resale/redistribute)", "#4 fuel oil", Material.Name,ignore.case = F, fixed = T)) %>% 
  mutate(Material.Name = gsub("#5 fuel oil (on-site consumption)", "#5 fuel oil", Material.Name,ignore.case = F, fixed = T)) %>% 
  mutate(Material.Name = gsub("#5 fuel oil (resale/redistribute)", "#5 fuel oil", Material.Name,ignore.case = F, fixed = T)) %>% 
  mutate(Material.Name = gsub("#6 fuel oil (on-site consumption)", "#6 fuel oil", Material.Name,ignore.case = F, fixed = T)) %>% 
  mutate(Material.Name = gsub("#6 fuel oil (resale/redistribute)", "#6 fuel oil", Material.Name,ignore.case = F, fixed = T)) %>%
  mutate(Material.Name = gsub("gasoline/ethanol", "ethanol", Material.Name,ignore.case = F, fixed = T)) %>% 
  mutate(Material.Name = gsub("Diesel (E-Gen)", "diesel", Material.Name,ignore.case = F, fixed = T)) %>% 
  mutate(Material.Name = gsub("used oil (heating, on-site consumption)", "used oil (heating)", Material.Name,ignore.case = F, fixed = T)) %>% 
  mutate(Material.Name = gsub("waste oil/used oil", "waste oil", Material.Name,ignore.case = F, fixed = T)) %>% 
  mutate(Material.Name = gsub("Biodiesel (E-Gen)", "biodiesel", Material.Name,ignore.case = F, fixed = T)) %>% 
  mutate(Material.Name = gsub("biodiesel (heating, on-site consumption)", "biodiesel", Material.Name,ignore.case = F, fixed = T)) %>% 
  
  mutate(Site.Type.Name = gsub("Municipality (Incl. Waste Water Treatment Plants, Utilities, Swimming Pools, etc.)", "Municipality", Site.Type.Name,ignore.case = F, fixed = T)) %>% 
  mutate(Site.Type.Name = gsub("Religious Building (Church, Synagogue, Mosque, Temple, etc.)", "Relgious Building", Site.Type.Name,ignore.case = F, fixed = T)) %>% 
  mutate(Site.Type.Name = gsub("Manufacturing (Other than Chemical)/Processing", "Non-Chemical Manufacturing/Processing", Site.Type.Name,ignore.case = F, fixed = T)) %>% 
  mutate(Site.Type.Name = gsub("Unknown", "Other", Site.Type.Name,ignore.case = F, fixed = T)) %>% 
  mutate(Site.Type.Name = gsub("Apartment Building/Office Building", "Apartment/Office Building", Site.Type.Name,ignore.case = F, fixed = T)) %>% 
  mutate(Site.Type.Name = gsub("Other Wholesale/Retail Sales", "Retail Gasoline Sales", Site.Type.Name,ignore.case = F, fixed = T)) %>% 
  mutate(Site.Type.Name = gsub("Auto Service/Repair (No Gasoline Sales)", "Auto Service", Site.Type.Name,ignore.case = F, fixed = T)) %>% 
  mutate(Site.Type.Name = gsub("Storage Terminal/Petroleum Distributor", "Petroleum Storage/Distribution", Site.Type.Name,ignore.case = F, fixed = T)) %>% 
  mutate(Site.Type.Name = gsub("Hospital/Nursing Home/Health Care", "Hospital/Health Care", Site.Type.Name,ignore.case = F, fixed = T)) %>% 
  mutate(Site.Type.Name = gsub("Airport/Airline/Air Taxi", "Airport", Site.Type.Name,ignore.case = F, fixed = T)) %>% 
  mutate(Site.Type.Name = gsub("Trucking/Transportation/Fleet Operation", "Trucking/Transport", Site.Type.Name,ignore.case = F, fixed = T)) %>% 
  
  mutate(Tank.Location = gsub("Aboveground - in contact with impervious barrier", "Aboveground (impervious barrier)", Tank.Location,ignore.case = F, fixed = T)) %>% 
  mutate(Tank.Location = gsub("Underground including vaulted with no access for inspection", "Underground (no access)", Tank.Location,ignore.case = F, fixed = T)) %>% 
  mutate(Tank.Location = gsub("Aboveground - in contact with soil", "Aboveground (soil contact)", Tank.Location,ignore.case = F, fixed = T)) %>% 
  mutate(Tank.Location = gsub("Aboveground on saddles, legs, stilts, rack or cradle"  ,"Aboveground (no ground contact)", Tank.Location,ignore.case = F, fixed = T)) %>%
  mutate(Tank.Location = gsub("Aboveground in Subterranean vault with access for inspections", "Aboveground (subterranean, with access)", Tank.Location,ignore.case = F, fixed = T)) %>% 
  mutate(Tank.Location = gsub("Tank with 10% or more below ground", "Tank (>10% below ground)", Tank.Location,ignore.case = F, fixed = T)) %>% 
  mutate(Locality = gsub("new york city", "new york", Locality,ignore.case = F, fixed = T)) %>% 
  mutate(County = gsub("New York City", "New York", County ,ignore.case = F, fixed = T))

```




```{r}
material_name = '#6 fuel oil'
closed = storage %>% 
  filter(Material.Name == material_name) %>% 
  group_by(Close.Date) %>% 
  summarise(sum_ = -sum(Capacity.in.Gallons)) %>% 
  rename(., 'Date' = 'Close.Date')


total = storage %>% 
  filter(Material.Name==material_name) %>% 
  group_by(Install.Date) %>% 
  rename(., 'Date' = 'Install.Date') %>% 
  summarise(sum_ = sum(Capacity.in.Gallons)) %>% 
  bind_rows(closed) %>% 
  arrange(Date) %>% 
  mutate(cumsum_ = cumsum(sum_)/1e6)


total %>% 
  ggplot(aes(x = Date, y = cumsum_)) +
  geom_step() +
  labs(title='Facility Install Date and Capacity',
       x='Install Date',
       y='Capacity') +
  scale_fill_brewer(palette='Set1') +
  theme_bw() +
  theme(legend.key=element_blank())
```
```{r}
storageFiltered %>% 
  group_by(Material.Name) %>% 
  ggplot(aes(x = Material.Name, y = Capacity.in.Gallons)) +
  geom_col() +
  labs(title='Total Capacity by Material',
       x='Sites',
       y='Capacity in Gallons') +
  scale_fill_brewer(palette='Set1') +
  theme_bw() +
  theme(legend.key=element_blank())
```
```{r}
storageFiltered %>% 
  ggplot(aes(x = reorder(Tank.Status,Capacity.in.Gallons, function(x) sum(x)), y = sum(Capacity.in.Gallons))) +
  geom_col(aes(fill=Material.Name)) +
  labs(title='Total Capacity by Material',
       x='Sites',
       y='Capacity in Gallons') +
  scale_fill_brewer(palette='Set1') +
  theme_bw() +
  coord_flip() + 
  theme(legend.key=element_blank())
```

```{r}
library(Hmisc)
library(psych)

storage_num = storage %>% select(Capacity.in.Gallons, Percent)
describe(storage_num)
```
```{r}
centiles = hist(storage$Rank, breaks = 20)$breaks

par(mfrow=c(1,2))
hist(storage$Rank,
     breaks = centiles,
     main = "Material Distribution",
     xlab = "Percentile",
     xlim = range(storage$Rank),
     col = '#00DD00',
     border = 'black')

hist(storage$Capacity.in.Gallons,
     breaks = 20)

actual = storage$Capacity.in.Gallons * storage$Percent
boxplot(storage$Rank)
boxplot(storage$Percent)
```
## Bivariate Graphical
```{r}
fig <- function(width, heigth){
     options(repr.plot.width = width, repr.plot.height = heigth)
}

material_name = "gasoline"
storage %>% 
  filter(Material.Name == material_name) %>% 
  ggplot(aes(x = Tank.Location, y = log(Capacity.in.Gallons))) +
  geom_violin() +
  coord_flip()

options(repr.plot.width = 14, repr.plot.height = 200)
storage %>% 
  filter(Material.Name == material_name) %>% 
  group_by(County) %>% 
  summarise(total = log(sum(Capacity.in.Gallons))) %>% 
  ggplot(aes(x = reorder(County,total), y = total)) +
  geom_point() +
  coord_flip()
```
```{r}
fig(102,100)
storage %>% 
  filter(Material.Name == material_name) %>% 
  group_by(County.Name) %>% 
  summarise(total = log(sum(Capacity.in.Gallons))) %>% 
  ggplot(aes(x = reorder(County.Name,total), y = total)) +
  geom_point() +
  theme()
```



```{r}
equitystats = read_csv('../data/equitystats_2004.csv')

```
```{r}
deaths = read_csv('../data/deaths_1957.csv')
```
```{r}
str(deaths)
```


```{r}
mortgages = read_csv('../data/mortgages_census.csv')
```

```{r}
str(mortgages)
```

```{r}
spills_byDEC = spills %>% 
  mutate(Year = lubridate::year(`Spill Date`)) %>% 
  filter(`Report Lag` > 0 & `Case Lag` > 0 & `Report Lag` < 1e3 & `Case Lag` < 1e3) %>% 
  group_by(Year,DEC.Region, County) %>% 
  summarise(Report.Lag = median(`Report Lag`), Case.Lag = median(`Case Lag`), Spills = n())
  
```

```{r}
spills_byDEC %>% 
  filter(DEC.Region == '1')

```

```{r}
spills_DEC_year = spills_byDEC %>%
  group_by(Year, DEC.Region) %>% 
  summarise(Report.Lag = mean(Report.Lag), Case.Lag=mean(Case.Lag), Spills = mean(Spills)) 
  
```

```{r}
spills_DEC_year %>% 
  filter(DEC.Region=='5') %>% 
  ggplot(aes(Year, Case.Lag)) +geom_path()
```

```{r}
spills %>% select(Material, Quantity) %>% arrange(desc(Quantity))
```

```{r}
spills %>% 
  mutate(month = lubridate::floor_date(`Spill Date`, 'month')) %>% 
  group_by(`Close Date`,month,`Spill Date`) %>%
  tally() %>% 
  summarise(total_month = sum(n)) %>% 
  mutate(cumsum = cumsum(total_month))
  
  
#%>% 
  #summarise(cumsum_ = cumsum(n()))
```

```{r}
hpi = read_csv('../../HPI_master.csv')

```

